### ISSUE TITLE
Can I read numpy data from the depth,normal and silhouette image?

### ISSUE THREAD

**Issue by CaolLiu** [xiumingzhang/GenRe-ShapeHD#58]
Hi,
I know that the depth,normal and silhouette image can be visualized from their numpy data, But can I read numpy data from the depth,normal and silhouette image?

**Comment by xiumingzhang** [comment]
Hi, sorry for the delayed response.

Are you referring to the raw, floating-point values? If so, you'd have to render the raw values with Mitsuba using our released XML files yourself.

Please feel free to reopen if you have further questions.

**Comment by CaolLiu** [comment]
Thank you for your reply.
 Are the raw, floating-point values obtained from .obj files by using the XML files ? And if I want to  obtain the raw muti-views  obj_spherical and the depth_spherical data from one three-dimensional model(as the each object captured in 20 random views), should I also use the XML files ?

**Comment by xiumingzhang** [comment]
By "using Mitsuba and the XML files," I meant rendering the depth, normal, and silhouette images into EXR files, and then reading the floating-point values from there.

You can of course do ray casting to the 3D model to get all these values (equivalent to doing the rendering yourself instead of with Mitsuba), but I think it'd be easier to just use Mitsuba.

**Comment by CaolLiu** [comment]
ok， thank you ^_^!
