### ISSUE TITLE
Full Dataset?

### ISSUE THREAD

**Issue by lyxhope** [xiumingzhang/GenRe-ShapeHD#69]
Thanks for your excellent paper and code. I have read the ShapeHD paper, in the 5th section, 3D shape reconstruction, when you tested on the synthetic data, you said that you trained on your rendering of the largest 13 shapenet categories, but in this code, I can only get dataset with three categories and pretrained model which is trained on the 3 categories. So is there a version of dataset and pretrained model on all 13 categories, even if the dataset has only 2D and 2.5D parts?
Thank you.

**Comment by xiumingzhang** [comment]
Hi, thanks for reaching out. IIRC, we released only our rendering of the largest three shape categories because these classes are the most common shape classes people work with, and just these three classes already made a huge .zip. If you need all 13 classes, you might need to render them yourself, unfortunately.
